### ISSUE TITLE
Decide upon Hardware Board

### ISSUE THREAD

**Issue by netzdoktor** [tl8roy/patina#2]
# Motivation

Making RustEmbedded accessible as part of Patina would require a single, go-to hardware board that everyone is using (much like Arduino).

# ToDo
* [ ]  Make sure all requirements are collected and specified
* [ ] Identify and collect existing boards
* [ ] Create a feature matrix for boards + requirements to filter down candidates

# Requirements

## Must-Haves

* Hardware must be Tier 1 supported ([Rust Platform Support List](https://forge.rust-lang.org/release/platform-support.html)).
* Price needs to be about $25-45 USD.
* Hardware must have a comprehensive Board Support Crate 
   * The BSP must come with examples 
   * The BSP should have clear references to up-to-date training resources
* Minimal RAM: TbD
* Minimal ROM: TbD
* Minimal CPU Frequency: TbD

## Nice-To-Haves
* Open sourced and cheap clone-able
* Wireless communications
   * If included, a complete and easy wireless stack is going to be needed
* QEMU support for the respective architecture to allow testing as a first step

## To Be Discussed
* Debugger or not?

# Collaborations & Partners
* Working with an existing supplier is fine as long as branding is clear
* Ferrous Systems offered to help in maintaining a "Ferrous-Supported Platform"

# Concrete Board (Families)
* Sparkfun Artemis 
* Adafruit Feather
* PJRC Teensy
* Potenta H7
* ESP
* nRF: 
  * 51: [micro:bit](https://microbit.org/), [calliope](https://calliope.cc/en), ...?
* STM32 (e.g. Discovery, BluePill)

# Feature Matrix (Sketch)

| Board / Feature | License | T1 Support               | Price | RAM | ROM | CPU | On-Chip Debugger | Wireless | ...  |
|-----------------|---------|----------------------|------|------|-------|------|---------------------|---------|----|
| ???                    |             | ![yes] / ![ehh] / ![no] | ???   | ???   | ???    | ???     | ???   | ???                           | ???       | ??? |

*Copy matrix styling from [Zola](https://github.com/getzola/zola)*

**Comment by tl8roy** [comment]
Unmentioned, but part of the success of Arduino: Open sourced and cheap clone-able

**Comment by michalfita** [comment]
While Arduino started with AVR, because at that time it make sense, today reality is different. The obvious choice for now is some ARM as RISC-V (that would be more in the spirit of openness) isn't mature enough for above needs. ESP wouldn't be my choice as this target is too vendor locked for my taste. Performance wise the board should aim for Cortex-M7 or Cortex-M33 (in the spirit of new secure features, however, they may not matter that much for hobbyist). Connectivity is important factor as well. Then Tier 1 support is a challenge.

In the spirit of open design, the board has to be drawn in open-source EDA: [LibrePCB](https://librepcb.org/), [Horizon EDA](https://horizon-eda.org/) or [KiCAD](https://kicad-pcb.org/) (_there are reasons why I've put KiCAD last, but I'm not starting discussion here_). The question whether for starter it's better to choose existing board or straight away use some as inspiration and do the open design remains open.

**Comment by TheZoq2** [comment]
> To Be Discussed

> Debugger or not?
I'm strongly in favour of having a debugger. I think not having one available at all needlessly complicates development. Especially with probe-rs which seems to be really simple to use

That said, an included bootloader by default is probably nice so people don't have to spend extra on a debugger and the intial setup might be easier

**Comment by tl8roy** [comment]
> 
> 
> > To Be Discussed
> 
> > Debugger or not?
> > I'm strongly in favour of having a debugger. I think not having one available at all needlessly complicates development. Especially with probe-rs which seems to be really simple to use
> 
> That said, an included bootloader by default is probably nice so people don't have to spend extra on a debugger and the intial setup might be easier

A boot loader with probe-rs in it? Can probe-rs probe itself?

**Comment by TheZoq2** [comment]
No, I meant a pre-flashed bootloader for the normal "arduino workflow". But with exposed debugger pins for when those are useful/

That's what the blue pill has, for example. (I think, I've always programmed it using the debugger)

**Comment by kevswims** [comment]
What about an easily attachable external debugger to save on the board cost and size? I would envision that this would normally be sold as a kit but then individuals could buy the boards standalone to use with a debugger they already have. Is there a standard connector/pinout for ARM debuggers? I haven't used very many of them.

**Comment by michalfita** [comment]
@kevswims There is standard 10 pin ARM connector, but I'd say that's waste of space if we don't want debugger on board. There are socket-less options offered on the market, but they usually involve expensive connector.

**Comment by kevswims** [comment]
Yeah, the 10 pin is big. It would really only need 6 pins max to give PWR, GND, SWCLK, SWDIO, RST, and SWO. 6pin tag connect would be great for board cost and space but the cables are expensive and not super durable. Something like this: https://www.digikey.com/product-detail/en/samtec-inc/TSM-106-01-T-SH-K-TR/SAM14849TR-ND/7632931 could be put on the edge of the board.
