### ISSUE TITLE
Discuss a strategy & structure for educational material

### ISSUE THREAD

**Issue by netzdoktor** [tl8roy/patina#9]
# Motivation

In order to get people intro RustEmbedded, there must be resources (guides / tutorials / ...) for various levels of knowledge.

# Tasks
* [ ] Identify "Personas" that want to learn Rust & Embedded (e.g. high school students, University students, young professionals)
* [ ] Structure material to fit these different audiences
* [ ] Bring collaborators onboard (e.g. teachers, lecturers, trainers, ...)

# Inspiration / Related Works
The EmbeddedRust WG already has two books "in print" that aim to fulfill a similar need:
* [Discovery Book](https://docs.rust-embedded.org/discovery/)
* [Embedded Book](https://docs.rust-embedded.org/book/index.html)
* [micro:bit Rust Book](https://droogmic.github.io/microrust/index.html)

While these books are great resources, they lack the following due to missing (human) resources:

* Regular updates to keep the material in sync with the state-of-the-arts crates. Examples:
  * The Discovery book has a custom HAL and examples cannot easily ported to the "production" HAL people shall be using
  * The books use tooling that is partially replaced by [probe-rs](https://probe.rs).

* Multiple languages (especially for beginner material it could be essential to have a couple of things in the native language)

**Comment by tl8roy** [comment]
My opinion is that there are 2 personas that I would consider 'low hanging fruit':
 - University students have a drive to push through things that are incomplete or not quite right. They also have some budget for hardware, but will generally prefer free and open source
- Javascript Developers know about big, complex code bases and JS is well known for not being ideal for programming big complex things. Showing them that there is another way while doing something cool is going to be a winner. They have the budget to buy new things (when they want to) assuming that it is sufficiently cool.

**Comment by netzdoktor** [comment]
Another persona would be:

Youths that got hooked into embedded systems by e.g. [Calliope](https://calliope.cc/en) and visual programming, but now want to try something more serious. 

The existing ways would be something like:
*  ECU + C or MicroPython,
*  Raspberry Pi + JS/Python/... 

But I can imagine that Rust + set of prepicked & high-quality crates with high levels of abstractions would allow them to get first textual programs done in a similar manner to JS/Python. As soon as they are familiar with that, they could start "unwrapping" the different abstractions... gradually making their way down to actual low-level stuff (registers, peripherals, ...).
